LGA-3093: Set up Google Analytics (#15)
* Move Tag Manager code snipped to its own block.

* Add gtm_anon_id to dataLayer

* Return early from detect_gtm_anon_id

* Simplified get_gtm_anon_id_from_cookie

* Default to "" if cookie is not present.

* Add environment parameter to Sentry

* No longer loads gtm when analytics cookie is not set.

* Refactored gtm code to its own file

* Use Tag Manager rather than GA

* Remove reference to non-existing component

* Remove undefined reference to gtm_body